# Generated by rust2rpm-9-1.fc31
%bcond_with check
%global debug_package %{nil}

%global crate secret-service

Name:           rust-%{crate}
Version:        1.0.0
Release:        3%{?dist}
Summary:        Library to interface with Secret Service API

# Upstream license specification: MIT OR Apache-2.0
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/secret-service
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
BuildRequires:  (crate(aes/default) >= 0.3.2 with crate(aes/default) < 0.4.0)
BuildRequires:  (crate(block-modes/default) >= 0.3.2 with crate(block-modes/default) < 0.4.0)
BuildRequires:  (crate(dbus/default) >= 0.2.3 with crate(dbus/default) < 0.3.0)
BuildRequires:  (crate(hkdf/default) >= 0.7.0 with crate(hkdf/default) < 0.8.0)
BuildRequires:  (crate(lazy_static/default) >= 1.3.0 with crate(lazy_static/default) < 2.0.0)
BuildRequires:  (crate(num/default) >= 0.2.0 with crate(num/default) < 0.3.0)
BuildRequires:  (crate(rand/default) >= 0.6.5 with crate(rand/default) < 0.7.0)
BuildRequires:  (crate(sha2/default) >= 0.8.0 with crate(sha2/default) < 0.9.0)

%global _description \
Library to interface with Secret Service API.

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE-MIT LICENSE-APACHE
%doc README.md
%{cargo_registry}/%{crate}-%{version}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Thu Jan 30 2020 Fedora Release Engineering <releng@fedoraproject.org> - 1.0.0-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Fri Jul 26 2019 Fedora Release Engineering <releng@fedoraproject.org> - 1.0.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Sun May 05 15:05:14 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.0-1
- Initial package
